### ISSUE TITLE
VCS support status

### ISSUE THREAD

**Issue by tianrui-wei** [Xilinx/systemctlm-cosim-demo#14]
Hi Edgar,

I was wondering if Synopsys VCS works for this demo. I saw there were some supports in Makefile, but they don't quite work. It'd be great if you could give me some pointers for get it working under VCS. Currently after some modifications, it reported `disconnected clk=0 ns`

Thanks
Tianrui

**Comment by edgarigl** [comment]
Hi Tianrui,

We've run similar demos with VCS but it was quite a while back (8 years ago or so).
My guess is that it won't work out of the box and the tlm-bridges/transactors may need some syscan options or editing.

Perhaps we (You, Francisco and myself) could setup a working session with screen share over zoom and see if we can figure things out?

Best regards,
Edgar

**Comment by tianrui-wei** [comment]
Hi Edgar,

Many thanks for your enthusiam in this matter! A zoom meeting would be great!

Best regards,
Tianrui

**Comment by tianrui-wei** [comment]
Thanks for merging the patch!
