### ISSUE TITLE
Confluence Documentation No Longer Reachable

### ISSUE THREAD

**Issue by Mluckydwyer** [Xilinx/systemctlm-cosim-demo#16]
The confluence page linked in the README regarding this Co-Simulation repo is no longer reachable as it is not behind an internal sign. I am not sure if this was intentional, but if so, it might be best to remove the link.

**Comment by edgarigl** [comment]
Hi!

When I copy the URL (http://www.wiki.xilinx.com/Co-simulation) I get automatically redirected to:
https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/862421112/Co-simulation

Does that not work for you?
Perhaps we should change it to point to
https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/862421112/Co-simulation
in that case..

Best regards,
Edgar

**Comment by Mluckydwyer** [comment]
Hello @edgarigl,

Sadly no. When I click or copy either of those links into my browser (or anyone on my team's) we get redirected to a Confluence sign-in page (https://id.atlassian.com/login?continue=https%3A%2F%2Fxilinx-wiki.atlassian.net%2Flogin%3FredirectCount%3D1%26dest-url%3D%252Fwiki%252Fspaces%252FA%252Fpages%252F862421112%252FCo-simulation%26application%3Dconfluence&application=confluence).

It looks like either that page or the entire wiki was made private some time ~1-2 weeks ago. Thank you for your assistance.
Respectfully,
Matthew Dwyer

**Comment by edgarigl** [comment]
Hi Matthew,

I talked to our marketing folks and they say these pages are supposed to be public. I also tried to access them from various locations here and seems to work without loging in. I wonder if there's something wrong with the redirection due to some caching? Could you try to refresh the reload? What happens if you load the page from your phone for example?

Best regards,
Edgar

**Comment by Mluckydwyer** [comment]
Hi Edgar,

I believe it might have been a caching issue. Reloading now gives me the correct page. There must have been some misconfiguration last week that was resolved today and my cache earlier had not updated. I am able to access it now using both the original and the redirect links. Thank you again!

Respectfully,
Matthew Dwyer

**Comment by edgarigl** [comment]
Great, thanks Matthew!
