### ISSUE TITLE
Use of Questa simulator instead of OSCI simulator

### ISSUE THREAD

**Issue by vlenoirSemtech** [Xilinx/systemctlm-cosim-demo#3]
Hello,

Recently I had the opportunity to work on Zynq-7000 chip to evaluate this design platform for future projects.

One of my interest was the co-simulation environment using QEMU and SystemC/TLM for design exploration and HW/FW partitioning. Based on the demo you provide on GitHub, I managed to run a simple application with QEMU accessing to some memory mapped virtual components on the TLM side.

Now, I was used in the past to use Questa simulator for SystemC instead of the OSCI provided one. I tried to compile the same demo using Questa with success, however at the end I realized that Questa runs as a “master” simulator, meaning that it has to control its own simulation time. Thus, once QEMU is launched and connected to the TLM side the simulation is suck.

Indeed in the base demo, the OSCI simulator is a “slave” for the QEMU “master” simulator which controls the time step. I’m therefore wondering if there is a way to use the libsystemctlm-soc library such a manner that the external SystemC/TLM simulator manage the CPU clock increment of QEMU ? Thus, the run command from Questa would control the firmware execution and not the other way.

Best regards,
Vincent Lenoir

**Comment by edgarigl** [comment]
Hi Vincent, sorry for the delay.

It's not really possible to do what you're asking for but it is possible to make QEMU run freely and detached from control of the SystemC side and vice-versa. I don't know if it will help with the Questa setup though.

To do that, you need to select the non-blocking socket mode when instantiating the zynq/remote-port object.

Cheers,
Edgar
