### ISSUE TITLE
QEMU not hang on TLM connection

### ISSUE THREAD

**Issue by mbaharan** [Xilinx/systemctlm-cosim-demo#4]
Hello, I am trying to do TLM co-simulation, however, the qemu hang on following connection, rather than systemc/TLM:
qemu-system-aarch64: -net nic,vlan=1: 'vlan' is deprecated. Please use 'netdev' instead.
qemu-system-aarch64: Failed to connect socket /home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/qemu_tmp/qemu-rport-_pmu@0: Connection refused
qemu-system-aarch64: info: QEMU waiting for connection on: disconnected:unix:/home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/qemu_tmp/qemu-rport-_pmu@0,server
-------------------
Here is my qemu command:
qemu-system-aarch64 -M arm-generic-fdt   -serial mon:stdio\
 -serial /dev/null -display none -device\
 loader,file=/home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/petalinux181/xilinx-zcu102-2018.1/images/linux/bl31.elf,cpu-num=0\
 -device loader,file=/home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/petalinux181/xilinx-zcu102-2018.1/images/linux/Image,addr=0x00080000\
 -device loader,file=/home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/petalinux181/xilinx-zcu102-2018.1/images/linux/system.dtb,addr=0x1407f000\
 -device loader,file=/home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/petalinux181/xilinx-zcu102-2018.1/build/misc/linux-boot/linux-boot.elf\
 -gdb tcp::9000 -dtb /home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/petalinux181/xilinx-zcu102-2018.1/images/linux/system.dtb\
 -net nic -net nic -net nic -net nic,vlan=1 -net user,vlan=1,tftp=/home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/petalinux181/xilinx-zcu102-2018.1/images/linux\
 -hw-dtb /home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/qemu-devicetrees/LATEST/MULTI_ARCH/zcu102-arm.cosim.dtb\
 -machine-path /home/reza/AxuHDD/WorkingDir/FPGA/ZCU102/qemu_tmp\
 -global xlnx,zynqmp-boot.cpu-num=0 -global xlnx,zynqmp-boot.use-pmufw=true  -m 4G
-------------------------------
My systemc/tlm version is 2.3.3 and I am using Vivado 18.1.
Any helps would be appreciated.
Thanks.

**Comment by edgarigl** [comment]
Hi,

This is happening because the ARM QEMU is waiting for the MicroBlaze/PMU QEMU machine to connect. You'll have to start all three simulations (QEMU-AArch64, QEMU-MicroBlaze and SystemC) for the full simulation to start.

Cheers,
Edgar
